spring:
  application:
    name: mybatis
  datasource:
      #url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
      #username: root
      #password: root
      url: jdbc:mysql://121.43.147.84:3306/joyosingletonpolicy?autoReconnect=true&useCompression=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: devsb02
      password: su3ZhISCpvOV
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true

  redis:
    database: 5
    host: 127.0.0.1
    pool:
      max-idle: 8
      min-idle: -1

server:
  port: 8095

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.joyowo.mybatis.pojo
logging:
  level: debug

eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/, http://peer2:1112/eureka/


